---
- name: Find project id
  ansible.builtin.include_tasks: list_project.yml

- name: Create EDA Project
  when: _project_id | length == 0
  ansible.builtin.uri:
    url: "{{ eda_controller_config_url }}/api/eda/v1/projects/"
    user: "{{ eda_controller_config_username }}"
    password: "{{ eda_controller_config_password }}"
    method: POST
    force_basic_auth: true
    validate_certs: false
    body_format: json
    status_code: 201
    body: >-
      {
        "name": "{{ item.name }}",
        "description": "{{ item.description | default(item.name) }}",
        "url": "{{ item.repo_url }}"
      }
