---
- name: Find decision_env id
  ansible.builtin.include_tasks: list_decision_env.yml
  vars:
    decision_env_name: "{{ item.name }}"

- name: Create Decision Environment
  when:
    - _decision_env_id | length == 0
  ansible.builtin.uri:
    url: "{{ eda_controller_config_url }}/api/eda/v1/decision-environments/"
    user: "{{ eda_controller_config_username }}"
    password: "{{ eda_controller_config_password }}"
    method: POST
    force_basic_auth: true
    validate_certs: false
    body_format: json
    status_code: 201
    body: >-
      {
        "name": "{{ item.name }}",
        "description": "{{ item.description | default(item.name) }}",
        "image_url": "{{ item.image_url }}"
      }
