---
- name: Find decision_env id
  ansible.builtin.include_tasks: list_decision_env.yml
  vars:
    decision_env_name: "{{ item.name }}"

- name: Find project id
  ansible.builtin.include_tasks: list_project.yml
  vars:
    project_name: "{{ item.name }}"

- name: Find rulebook id
  ansible.builtin.include_tasks: list_rulebook.yml
  vars:
    rulebook_name: "{{ item.rulebook }}"

- name: Find activation id
  ansible.builtin.include_tasks: list_activation.yml
  vars:
    rulebook_activation_name: "{{ item.name }}"

- name: Create Rulebook Activation
  when:
    - _activation_id | length == 0
    - _project_id | length > 0
    - _rulebook_id | length > 0
    - _decision_env_id | length > 0
  ansible.builtin.uri:
    url: "{{ eda_controller_config_url }}/api/eda/v1/activations/"
    user: "{{ eda_controller_config_username }}"
    password: "{{ eda_controller_config_password }}"
    method: POST
    force_basic_auth: true
    validate_certs: false
    body_format: json
    status_code: 201
    body: >-
      {
        "name": "{{ item.name }}",
        "description": "{{ item.description | default(item.name) }}",
        "project_id": "{{ _project_id }}",
        "rulebook_id": "{{ _rulebook_id }}" ,
        "decision_environment_id": "{{ _decision_env_id }}",
        "restart_policy": "{{ item.restart_policy | default('always')}}",
        "is_enabled": "{{ item.enabled | default(true) }}"
      }
