---
- name: List Decision Environments
  ansible.builtin.uri:
    url: "{{ eda_controller_config_url }}/api/eda/v1/decision-environments/"
    user: "{{ eda_controller_config_username }}"
    password: "{{ eda_controller_config_password }}"
    method: GET
    force_basic_auth: true
    validate_certs: false
    body_format: json
    status_code: 200
  register: _r_list_de

- name: List decision environments
  ansible.builtin.debug:
    msg: "{{ _r_list_de.json.results }}"
    verbosity: 2

- name: Find decision env id
  vars:
    _query: '[?name == `{{ item.decision_env }}`].id'
  ansible.builtin.set_fact:
    _decision_env_id: "{{ _r_list_de.json.results | json_query(_query) | join }}"

- name: "Decision Env ID [{{ item.decision_env }}]"
  ansible.builtin.debug:
    msg: "{{ _decision_env_id }}"
